/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WorkoutSet = IDL.Record({
  'weight' : IDL.Float64,
  'reps' : IDL.Nat,
});
export const ExerciseLog = IDL.Record({
  'exerciseId' : IDL.Nat,
  'sets' : IDL.Vec(WorkoutSet),
  'exerciseName' : IDL.Text,
});
export const DayType = IDL.Variant({
  'rust' : IDL.Null,
  'kracht' : IDL.Null,
  'cardio' : IDL.Null,
});
export const WorkoutSession = IDL.Record({
  'date' : IDL.Text,
  'exercises' : IDL.Vec(ExerciseLog),
  'dayType' : DayType,
});

export const idlService = IDL.Service({
  'getAllLogs' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
  'logWorkout' : IDL.Func([WorkoutSession], [], []),
  'register' : IDL.Func([], [], []),
  'updateSchedule' : IDL.Func([IDL.Nat, DayType], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WorkoutSet = IDL.Record({ 'weight' : IDL.Float64, 'reps' : IDL.Nat });
  const ExerciseLog = IDL.Record({
    'exerciseId' : IDL.Nat,
    'sets' : IDL.Vec(WorkoutSet),
    'exerciseName' : IDL.Text,
  });
  const DayType = IDL.Variant({
    'rust' : IDL.Null,
    'kracht' : IDL.Null,
    'cardio' : IDL.Null,
  });
  const WorkoutSession = IDL.Record({
    'date' : IDL.Text,
    'exercises' : IDL.Vec(ExerciseLog),
    'dayType' : DayType,
  });
  
  return IDL.Service({
    'getAllLogs' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
    'logWorkout' : IDL.Func([WorkoutSession], [], []),
    'register' : IDL.Func([], [], []),
    'updateSchedule' : IDL.Func([IDL.Nat, DayType], [], []),
  });
};

export const init = ({ IDL }) => { return []; };